### PR TITLE
multi stage docker

### LINKED ISSUE #11: Request: prebuilt docker container
That would make trying this out much easier!

### PR DESCRIPTION
**Pull request by fbartels**
fixes #11

Signed-off-by: Felix Bartels <felix@host-consultants.de>

### CODE REVIEW

**Comment by fbartels** [comment]
The last stage is now much smaller:
```
 $ docker images | grep toodles
toodles                                          latest                         5eb909f6e2aa        58 seconds ago       92.1MB
```

**Comment by aviaviavi** [comment]
Is there a specific version of docker I need to get this working? 

```
~/s/toodles ❯❯❯ docker build -t toodles .
Sending build context to Docker daemon 169.6 MB
Step 1 : FROM haskell:8.4 as build-env
Error parsing reference: "haskell:8.4 as build-env" is not a valid repository/tag
```

**Comment by fbartels** [comment]
Hi,

yes indeed. Multi stage builds require Docker 17.05: https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by aviaviavi** [comment]
Got it, will try again shortly

**Comment by aviaviavi** [comment]
This is looks great, thanks @fbartels. Just pushed this to dockerhub (aviaviavi/toodles), seems to be working nicely :D

**Pull request merged**
