### PR TITLE
Add txt support

### PR DESCRIPTION
**Pull request by damiencourousse**

### CODE REVIEW

**Comment by aviaviavi** [comment]
Yeah @damiencourousse if you don't mind, that would be good to add here. Once this and the php pr is merged I'll release a new version to hackage (and probably some precompiled binaries too)

**Comment by damiencourousse** [comment]
Yes sure ! Will do ASAP.

**Comment by damiencourousse** [comment]
Do you prefer that I add another commit or that I edit / amend this one?

**Comment by aviaviavi** [comment]
No preference so whatever's easier

**Comment by damiencourousse** [comment]
Here comes an updated change for this pull request.

Thanks for this tool! It looks like your repository has gained momentum in the few past days ;)

**Comment by aviaviavi** [comment]
So glad you're finding it useful :) 

Yeah the response from the community here has been great, very exciting :D

**Pull request merged**
