### PR TITLE
restructure & remove unused

### PR DESCRIPTION
**Pull request by jahaynes**
- Broke Main.hs up into a few modules
- Removed some unused dependencies from package.yaml
- Some minor refactoring

### CODE REVIEW

**Comment by aviaviavi** [comment]
@jahaynes: I haven't had a chance to read through this yet but I just want to say this PR is awesome and you are awesome for doing it :) 

I should have time to read through this tonight and will either merge or leave any feedback.

**Comment by damiencourousse** [comment]
@aviaviavi please could you review the changes proposal [here](https://github.com/aviaviavi/toodles/compare/master...damiencourousse:flags#diff-63e7d2cbf23880a9c902c91fa34f6043R1)?   I will then rebase on master and update if need be.

**Comment by aviaviavi** [comment]
@damiencourousse are you saying you want to rebase your change on top of master after this PR? Between the change you linked and this change, I'm happy to merge in either order, whatever is easier for you both.

**Comment by aviaviavi** [comment]
@damiencourousse would you mind opening up a separate PR for your changes? Your changes are solid and just had a few pieces of feedback.

@jahaynes this is looking great. I accidentally just created some a conflict by merging another PR, so I will fix them myself locally and merge your changes that way. I'm still getting the hang of managing several changes at once like this

**Pull request merged**
