### PR TITLE
Add html and css support

### PR DESCRIPTION
**Pull request by ekinertac**

### CODE REVIEW

**Comment by aviaviavi** [comment]
Thanks so much for submitting this @ekinertac! So one thing here - it seems like both of these comment indicator characters also have closing tags, so am I correct in thinking this currently include `-->` and `*/` in the TODO body?

**Comment by ekinertac** [comment]
Hey @aviaviavi thanks for the fast feedback and yes .html and .css comments includes closings tags as `-->` and `*/` but i can't find where to place these closing tags in your code :)

**Comment by aviaviavi** [comment]
Ah right, so doing this fully will actually involve making a small change to the parser. At the very end, you'd want to strip off that closing tag. See `parseTodo` in Main.hs.

Then, we'd need to make sure to add the closing tag back on the rendering side, so that when we make edit's to the TODO we insert the close tag properly.

**Comment by LifeCoder45** [comment]
Would it be possible to also map `<!--` & `-->` to the extensions:

- `.xaml` (XAML, Xamarin / WPF / UWP UI files) 
- `.xml` (XML, serialization / config / etc) 

as well, when the close tag is fixed up in this PR, since it's the same tokens? If not, I can PR subsequently after this is fixed up and merged.

**Comment by aviaviavi** [comment]
@ekinertac let me know if you need any help! (Also totally no sweat if this change was larger than you anticipated, just lmk)

**Pull request closed without merging**
